### ISSUE TITLE
How can I get `mean_shapes.npy`  file?

### ISSUE THREAD

**Issue by eclipse0922** [CNJianLiu/MH6D#2]
Thank you for sharing amazimg works.

I have question about the file missing.

The 'mean_shapes.npy' file seems not part of original NOCS dataset(CAMERA, Real)

How can I get this file?

**Comment by CNJianLiu** [comment]
Thanks for your interest in our work. The "mean_shapes.npy" file can be directly obtained from [SPD](https://github.com/mentian/object-deformnet/blob/master/assets/mean_points_emb.npy).

**Comment by eclipse0922** [comment]
@CNJianLiu Thank you!

**Comment by eclipse0922** [comment]
@CNJianLiu Thank you!
